apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-cf-mongo
  name: easytravel-cf-mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-cf-mongo
    spec:
      containers:
      - image: registry.lab.dynatrace.org/demoability/easytravel-mongodb:latest
        name: easytravel-cf-mongo
        ports:
        - containerPort: 27017
        - containerPort: 28017
        resources: {}
      restartPolicy: Always
status: {}
