apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: loadgen
  name: loadgen
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: loadgen
      annotations:
        support.contact: "demoability@dynatrace.com"
        support.channel: "#team-demoability"
    spec:
      containers:
      - env:
        - name: ET_APM_SERVER_DEFAULT
          value: APM
        - name: ET_FRONTEND_URL
          value: http://ls-cs-s11v.dynatrace.vmta:30683
        - name: ET_PROBLEMS
          value: BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox
        image: registry.lab.dynatrace.org/demoability/easytravel-loadgen:latest
        imagePullPolicy: Always
        name: loadgen
        resources: {}
      restartPolicy: Always
status: {}
